# -*- coding: utf-8 -*-
"""Task Bootcamp Data Science2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cQqSTJJMmlphDQHCM63RlXZdCcFesmtH
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv(r"/content/Data Science Bootcamp Week2.csv")
print(df)

"Date" = df["Date"]
print("Date")

plt.figure(figsize= (15,10))
x = df['Date']
y = df['Averange']
plt.scatter(x,y, color = "black", marker = "*")
plt.title("Perkembangan Alur Keuangan")
plt.xlabel("Date")
plt.ylabel("Averange")
plt.show()

